name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.123.4/hugo_extended_0.123.4_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo
      - name: Clear cache
        run: |
          rm -rf ~/.cache/hugo
          
      - name: Build
        run: ${RUNNER_TEMP}/hugo --verbose

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add -A
          git config user.name 'mishra39'
          git config user.email 'akshitmishra1995@gmail.com'
          git commit -m 'Updated site' || echo "No changes to commit"
          git push 
      - name: Debug Output
        run: |
          echo "Contents of public directory:"
          ls -la public/
          echo "Contents of built-site directory before copy:"
          ls -la ${GITHUB_WORKSPACE}/built-site/
          echo "Contents of built-site directory after copy:"
          ls -la ${GITHUB_WORKSPACE}/built-site/
